CREATE TABLE STATION
(
ID INT(20) PRIMARY KEY,
CITY CHAR(20),
STATE CHAR(2),
LAT_N INT(10),
LONG_W INT(10)
);

INSERT INTO STATION VALUES (13, "PHOENIX", "AZ", 33, 112);
INSERT INTO STATION VALUES (44, "DENVER", "CO", 40, 105);
INSERT INTO STATION VALUES (66, "CARIBOU", "ME", 47,68);

SELECT * FROM STATION WHERE LAT_N > 39.7;


CREATE TABLE STATS
(
ID INT(10),
MONTH INT(2), CHECK (MONTH BETWEEN 1 AND 12),
TEMP_F DECIMAL (5,2), CHECK (TEMP_F BETWEEN -80 AND 150),
RAIN_I DECIMAL(5,2), CHECK (RAIN_I BETWEEN 0 AND 100),
PRIMARY KEY (ID, MONTH)
);
INSERT INTO STATS VALUES(13, 1, 57.4, .31);
INSERT INTO STATS VALUES(13, 7, 91.7, 5.15);
INSERT INTO STATS VALUES(44, 1, 27.3, .18);
INSERT INTO STATS VALUES(44, 7, 74.8, 2.11);
INSERT INTO STATS VALUES(66, 1, 6.7, 2.1);
INSERT INTO STATS VALUES(66, 7, 65.8, 4.52);

SELECT STATION.CITY,STATS.MONTH, STATS.TEMP_F 
FROM STATION JOIN STATS ON STATION.ID= STATS.ID;


SELECT  STATS.ID, STATION.CITY, STATS.MONTH, STATS.RAIN_I AS Greatest_Rainfall
FROM STATS JOIN STATION ON STATS.ID = STATION.ID ORDER BY STATS.RAIN_I DESC;

SELECT STATION.CITY, STATION.LAT_N, STATS.MONTH, STATS.TEMP_F AS TEMPERATURE 
FROM STATS JOIN STATION ON STATS.ID= STATION.ID 
WHERE STATS.MONTH= 7 ORDER BY TEMP_F ASC;

SELECT STATION. CITY, MAX(STATS.TEMP_F) AS MAX_TEMPERATURE, MIN(STATS.TEMP_F) 
AS MIN_TEMPERATURE, AVG(STATS.RAIN_I) AS AVERAGE_RAINFALL 
FROM STATS JOIN STATION ON STATS.ID= STATION.ID GROUP BY STATION.CITY;

SELECT STATION.CITY, STATS.MONTH,((STATS.TEMP_F - 32) * 5/9) AS Temperature_Celsius,
(STATS.RAIN_I * 2.54) AS Rainfall_Centimeter FROM STATS JOIN STATION ON STATS.ID= STATION.ID;

UPDATE STATS SET RAIN_I= (RAIN_I + 0.01) WHERE ID = 13;
UPDATE STATS SET RAIN_I= (RAIN_I + 0.01) WHERE ID = 44;
UPDATE STATS SET RAIN_I= ( RAIN_I + 0.01) WHERE ID = 66;

SELECT * FROM STATS;
